services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: telecom
      POSTGRES_USER: telecom
      POSTGRES_PASSWORD: telecom123

    ports:
      - "5432:5432"

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql   # minúscula

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telecom -d telecom"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  midpoint:
    build:
      context: ./midpoint
    container_name: midpoint
    environment:
      MP_SET_midpoint_repository_jdbcUrl: "jdbc:postgresql://postgres:543docker exec -it midpoint bash2/midpoint"
      MP_SET_midpoint_repository_jdbcUsername: "telecom"
      MP_SET_midpoint_repository_jdbcPassword: "telecom123"
      MP_SET_midpoint_repository_database: "postgresql"
      JAVA_OPTS: "-Xmx2048m"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy   # espera a que postgres esté listo

  asterisk:
    image: andrius/asterisk:latest

    container_name: asterisk

    ports:
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"

    volumes:
      - ./asterisk/sip.conf:/etc/asterisk/sip.conf
      - ./asterisk/extensions.conf:/etc/asterisk/extensions.conf

    depends_on:
      - midpoint

networks:
  default:
    driver: bridge